[pytest]
testpaths = APP WEB INTEGRACION
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Salida detallada
addopts =
    -v
    --tb=short
    --json-report
    --json-report-file=resultados/pytest_resultados.json

# Filtros de warnings
filterwarnings =
    ignore::DeprecationWarning
    ignore::urllib3.exceptions.InsecureRequestWarning

# Timeout por test (segundos)
timeout = 35
